import React from 'react';
// Warning!
// Autogenerated - do not edit.
// Edit SVG icons in public/images/icons and run: ./script/generators/render-icons
export default class BEFlagIcon extends React.Component {
  displayName = 'BEFlagIcon'

  static propTypes = {
    className: React.PropTypes.string,
  };

  /*eslint-disable max-len*/
  render() {
    return (
      <svg {...this.props} id="svg554" height={480} width={640} author="Daniel McRae">
      <g id="flag" fill-rule="evenodd" transform="matrix(1.0947 0 0 .94732 0 -5.0275)" strokeWidth="1pt">
        <rect id="rect558" height="506.69" width="194.88" y="5.3071" x={0} />
        <rect id="rect559" height="506.69" width="194.88" y="5.3071" x="194.88" fill="#ffd90c" />
        <rect id="rect560" height="506.69" width="194.88" y="5.3071" x="389.76" fill="#f31830" />
      </g>
    </svg>

    );
  }
}

