import React from 'react';
// Warning!
// Autogenerated - do not edit.
// Edit SVG icons in public/images/icons and run: ./script/generators/render-icons
export default class DEFlagIcon extends React.Component {
  displayName = 'DEFlagIcon'

  static propTypes = {
    className: React.PropTypes.string,
  };

  /*eslint-disable max-len*/
  render() {
    return (
      <svg {...this.props} height={480} width={640}>
      <g id="flag" fill-rule="evenodd" strokeWidth="1pt" transform="matrix(.60207 0 0 .75259 0 -.000028157)">
        <rect id="rect171" height="212.6" width={1063} y="425.2" x={0} fill="#ffe600" />
        <rect id="rect256" height="212.6" width={1063} y="0.000038" x={0} />
        <rect id="rect255" height="212.6" width={1063} y="212.6" x={0} fill="#f00" />
      </g>
    </svg>

    );
  }
}

