import React from 'react';
// Warning!
// Autogenerated - do not edit.
// Edit SVG icons in public/images/icons and run: ./script/generators/render-icons
export default class FRFlagIcon extends React.Component {
  displayName = 'FRFlagIcon'

  static propTypes = {
    className: React.PropTypes.string,
  };

  /*eslint-disable max-len*/
  render() {
    return (
      <svg {...this.props} height={480} width={640} version={1}>
      <g id="g3627" fill-rule="evenodd" strokeWidth="1pt" transform="scale(1.25 .9375)">
        <rect id="rect171" height={512} width={512} y="7.4219e-7" x={0} fill="#fff" />
        <rect id="rect403" height={512} width="170.67" y="7.4219e-7" x={0} fill="#00267f" />
        <rect id="rect135" height={512} width="170.67" y="7.4219e-7" x="341.33" fill="#f31830" />
      </g>
    </svg>

    );
  }
}

