import React from 'react';
// Warning!
// Autogenerated - do not edit.
// Edit SVG icons in public/images/icons and run: ./script/generators/render-icons
export default class IEFlagIcon extends React.Component {
  displayName = 'IEFlagIcon'

  static propTypes = {
    className: React.PropTypes.string,
  };

  /*eslint-disable max-len*/
  render() {
    return (
      <svg {...this.props} height={480} width={640}>
      <g fill-rule="evenodd" strokeWidth="1pt" transform="matrix(.64234 0 0 .98016 0 -6.2203)">
        <rect id="rect171" height="489.72" width="996.35" y="6.3462" x={0} fill="#fff" />
        <rect id="rect403" height="489.72" width="332.12" y="6.3462" x={0} fill="#009A49" />
        <rect id="rect135" height="489.72" width="332.12" y="6.3462" x="664.24" fill="#FF7900" />
      </g>
    </svg>

    );
  }
}

