export default {
  siteName: 'GoCardless',
  companyName: 'GoCardless Ltd.',
  logoUrlSquare: 'https://gocardless.com/images/logos/gocardless-square.png',
  googleSiteVerification: 'Y80kah87ghJhwiDqw-5ap234p9wCcGt6kMRxvnamtHU',
  socialLinks: {
    facebook: 'https://www.facebook.com/GoCardless',
    twitter: 'https://twitter.com/gocardless',
    google: 'https://plus.google.com/+Gocardless',
    linkedin: 'https://www.linkedin.com/company/gocardless',
    github: 'http://github.com/gocardless',
  },
  team: [
    'Octave Auger',
    'Grey Baker',
    'Baris Balic',
    'Angus Bayley',
    'James Berry',
    'Lewis Blackwood',
    'George Britton',
    'Jenna Brown',
    'Maria Campbell',
    'Michael Christofides',
    'Duncan Coleman',
    'James Cunningham',
    'Amaury de Closset',
    'Steve Domin',
    'Jamie English',
    'Jack Franklin',
    'Jessie Giladi',
    'Pete Hamilton',
    'Phil Harrison',
    'Natalie Hockham',
    'James Jackson',
    'Sam Jewell',
    'Alan Kennedy',
    'Georg Knoerr',
    'Norberto Lopes',
    'Daniel Lyons',
    'Harry Marr',
    'Erez Mathan',
    'Ben Miller',
    'Max Murdoch',
    'Iain Nash',
    'Jacob Pargin',
    'Tom Petty',
    'Nabeel Qureshi',
    'Matt Robinson',
    'Tim Rogers',
    'Isaac Seymour',
    'James Shedden',
    'Ben Sims',
    'Chris Sinjakli',
    'Dave Smith',
    'Alina Solovjova',
    'Jess Summerfield',
    'Hiroki Takeuchi',
    'Yoshio Takeuchi',
    'Helen Taylor',
    'Corinne Thompson',
    'Matt Thomson',
    'James Walker',
  ],
};
