#!/bin/bash
# Usage: script/e2e

PORT='4402'

# if something is on our port, bail out and shout
echo exit | nc localhost $PORT
if [ $? -eq 0 ]; then
  echo "something is already running on $PORT"
  exit 1
fi

set -e errexit

./script/build-prod

./node_modules/.bin/serve -p $PORT dist/ &>.e2e_server_log &
SERVER_PID=$!

# wait for the server to be up and running
while ! echo exit | nc localhost $PORT; do sleep 1; done

# at this point on, we want it to not exit even if protractor fails
# so we can kill the server process
set +e errexit

./node_modules/.bin/protractor config/protractor.config.js

PROTRACTOR_EXIT=$?

kill $SERVER_PID

exit $PROTRACTOR_EXIT
