#!/bin/bash
# Usage: script/start
# Starts the projects's development server.

set -e errexit

ulimit -n 10240

nodemon ./index.js --ignore '*' --watch ./restart.txt --ext txt &

babel-node ./webpack/server.js
