#!/bin/bash
# Usage: script/start
# Starts the projects's development server.

set -e errexit

ulimit -n 10240

nodemon ./index.js --watch 'env' --ext 'txt' &

babel-node ./webpack/server.js

trap 'trap - SIGTERM && kill 0' SIGINT SIGTERM EXIT

