#!/bin/bash
# Usage: script/start
# Starts the projects's development server.

set -e errexit

ulimit -n 10240

./node_modules/.bin/nodemon ./index.js --watch 'env' --ext 'txt' &

./node_modules/.bin/babel-node ./webpack/server.js

trap "trap - SIGTERM && kill -- -$$" SIGINT SIGTERM EXIT

